version: 0.2

phases:
  pre_build:
    commands:
      # We remove these folders so we can symlink them to the
      # docker image's resources instead.
      - rm cache config -r
      - ln -s /root/config config
      - ln -s /root/cache cache

  build:
    commands:
      # Runs our tests and makes our binary
      - mvn package

  post_build:
    commands:
      # Clean up extra files we created
      - rm cache config

artifacts:
  files:
    - target/titan-1.0.jar

  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'
