version: '2'

services:
    db:
        build:
            context: ./src/main/docker/mysql
        ports:
            - "3306:3306"

    titan:
        image: titan

        depends_on:
            - db

        environment:
            - "DATABASE_TYPE=mysql"
            - "DATABASE_HOST=db"
            - "DATABASE_USER=root"
            - "DATABASE_PASS="
            - "DATABASE_DATABASE=titan"
            - "DATABASE_PORT=3306"

        ports:
            - "43594:43594"

        build:
            context: .
